name: Build and Push Authentication Service Image to ACR

on:
  push:
    paths:
      - 'authentication-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_SECRET_KEY: ${{ secrets.CLOUDINARY_SECRET_KEY }}
      ADMIN_EMAIL : ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD : ${{ secrets.ADMIN_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry using Access Key
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image with environment variables
        run: |
          docker build \
            --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} \
            --build-arg CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }} \
            --build-arg CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
            --build-arg CLOUDINARY_SECRET_KEY=${{ secrets.CLOUDINARY_SECRET_KEY }} \
            --build-arg ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} \
            --build-arg ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -f authentication-service/Dockerfile \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/authentication-service:latest \
            authentication-service

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/authentication-service:latest
